# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Avalon' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Avalon
	pod 'Firebase/Analytics'
	pod 'Firebase/Database'	
	pod 'SharedCode', :path => '/Users/maxtauro/Documents/Avalon/Avalon/SharedCode'

  target 'AvalonTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AvalonUITests' do
    # Pods for testing
  end

end
